### ISSUE TITLE
Backend build is broken

### ISSUE THREAD

**Issue by praseodym** [kiesraad/abacus#1614]
The backend build with a local database (so without setting `SQLX_OFFLINE=true`) is broken due to sqlx being unhappy about a query used in tests:

```bash
git clone git@github.com:kiesraad/abacus.git
cd abacus/backend
sqlx database setup
cargo check --all-targets
```

Result:
```
    Checking abacus v0.1.0 (/private/tmp/abacus/backend)
error: no built in mapping found for type NULL of column #2 ("event"); a type override may be required, see documentation for details
   --> src/data_entry/api.rs:772:29
    |
772 |         let audit_log_row = query!("SELECT * FROM audit_log ORDER BY id DESC LIMIT 1")
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `query` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `(): sqlx::Decode<'_, Sqlite>` is not satisfied
   --> src/data_entry/api.rs:772:29
    |
772 |         let audit_log_row = query!("SELECT * FROM audit_log ORDER BY id DESC LIMIT 1")
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `sqlx::Decode<'_, Sqlite>` is not implemented for `()`
    |
    = help: the following other types implement trait `sqlx::Decode<'r, DB>`:
              `&'a str` implements `sqlx::Decode<'a, sqlx::Any>`
              `&'r JsonRawValue` implements `sqlx::Decode<'r, DB>`
              `&'r [u8]` implements `sqlx::Decode<'r, Sqlite>`
              `&'r [u8]` implements `sqlx::Decode<'r, sqlx::Any>`
              `&'r str` implements `sqlx::Decode<'r, Sqlite>`
              `Box<[u8]>` implements `sqlx::Decode<'_, Sqlite>`
              `Box<str>` implements `sqlx::Decode<'_, Sqlite>`
              `Cow<'r, str>` implements `sqlx::Decode<'r, Sqlite>`
            and 45 others
note: required by a bound in `try_get_unchecked`
   --> /Users/mark/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/sqlx-core-0.8.6/src/row.rs:155:12
    |
152 |     fn try_get_unchecked<'r, T, I>(&'r self, index: I) -> Result<T, Error>
    |        ----------------- required by a bound in this associated function
...
155 |         T: Decode<'r, Self::Database>,
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `Row::try_get_unchecked`
    = note: this error originates in the macro `$crate::sqlx_macros::expand_query` which comes from the expansion of the macro `query` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
    --> src/data_entry/api.rs:778:61
     |
778  |         let event: serde_json::Value = serde_json::from_str(&audit_log_row.event).unwrap();
     |                                        -------------------- ^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `&()`
     |                                        |
     |                                        arguments to this function are incorrect
     |
     = note: expected reference `&str`
                found reference `&()`
note: function defined here
    --> /Users/mark/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/serde_json-1.0.140/src/de.rs:2697:8
     |
2697 | pub fn from_str<'a, T>(s: &'a str) -> Result<T>
     |        ^^^^^^^^

Some errors have detailed explanations: E0277, E0308.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `abacus` (lib test) due to 4 previous errors
```

`git bisect` marks 3ebb31e898ce2c737807799b3b92c03508994cd0 as the first bad commit. This commit introduced this query. I'm not sure how things compiled when this query was written in the first place.
